<flat-profile>
	<Second_Dial_Tone>420@-19;10(*/0/1)</Second_Dial_Tone>
	<Block_ANC_Serv_1_>No</Block_ANC_Serv_1_>
	<SIP_TOS_DiffServ_Value_1_>0x68</SIP_TOS_DiffServ_Value_1_>
	<Outbound_Proxy_1_>bks.tv</Outbound_Proxy_1_>
	<Ring2_Name>Bellcore-r2</Ring2_Name>
	<Speed_Dial_Act_Code></Speed_Dial_Act_Code>
	<Ring_On_No_New_VM_2_>Yes</Ring_On_No_New_VM_2_>
	<Jitter_Buffer_Adjustment_1_>up only</Jitter_Buffer_Adjustment_1_>
	<FAX_Passthru_Codec_2_>G711a</FAX_Passthru_Codec_2_>
	<Speed_Dial_4_1_></Speed_Dial_4_1_>
	<Ring6_Caller_1_></Ring6_Caller_1_>
	<Dist_Ring_Setting_1_>Yes</Dist_Ring_Setting_1_>
	<Handle_VIA_rport>No</Handle_VIA_rport>
	<Restrict_Source_IP_1_>No</Restrict_Source_IP_1_>
	<Interdigit_Long_Timer>7</Interdigit_Long_Timer>
	<Daylight_Saving_Time_Rule>start=4/1/7;end=10/-1/7;save=1</Daylight_Saving_Time_Rule>
	<CWCID_Serv_2_>No</CWCID_Serv_2_>
	<G723_Enable_1_>No</G723_Enable_1_>
	<Cfwd_Sel2_Caller_2_></Cfwd_Sel2_Caller_2_>
	<Cfwd_Last_Deact_Code></Cfwd_Last_Deact_Code>
	<DND_Serv_2_>No</DND_Serv_2_>
	<Forced_Resync_Delay>151200</Forced_Resync_Delay>
	<Reg_Retry_Intvl_Cap></Reg_Retry_Intvl_Cap>
	<SIP_Reg_User_Agent_Name></SIP_Reg_User_Agent_Name>
	<Speed_Dial_3_1_></Speed_Dial_3_1_>
	<VMWI_Refresh_Intvl>0</VMWI_Refresh_Intvl>
	<Prefer_G711a_Code></Prefer_G711a_Code>
	<Secure_One_Call_Act_Code></Secure_One_Call_Act_Code>
	<Primary_DNS>77.232.128.1</Primary_DNS>
	<STUN_Test_Enable>No</STUN_Test_Enable>
	<DNS_SRV_Auto_Prefix_1_>Yes</DNS_SRV_Auto_Prefix_1_>
	<SIT2_Tone>914@-16,1371@-16,1777@-16;20(.274/0/1,.274/0/2,.380/0/3,0/4/0)</SIT2_Tone>
	<Caller_ID_Method>Bellcore(N.Amer,China)</Caller_ID_Method>
	<Cfwd_Sel8_Dest_2_></Cfwd_Sel8_Dest_2_>
	<Prefer_G729a_Code></Prefer_G729a_Code>
	<Hook_Flash_Timer_Max>.9</Hook_Flash_Timer_Max>
	<Force_G726r32_Code></Force_G726r32_Code>
	<Cfwd_Sel3_Caller_1_></Cfwd_Sel3_Caller_1_>
	<Interdigit_Short_Timer>2</Interdigit_Short_Timer>
	<Profile_Rule>/linksys.cfg</Profile_Rule>
	<Restricted_Access_Domains></Restricted_Access_Domains>
	<MOH_Server_1_></MOH_Server_1_>
	<Force_G711a_Code></Force_G711a_Code>
	<VMWI_Ring_Policy_2_>New VM Available</VMWI_Ring_Policy_2_>
	<Ring_Back_Tone>440@-19;*(2/4/1)</Ring_Back_Tone>
	<Primary_NTP_Server>77.232.128.1</Primary_NTP_Server>
	<SIP_Port_2_>5160</SIP_Port_2_>
	<Block_ANC_Setting_2_>No</Block_ANC_Setting_2_>
	<Profile_Rule_C></Profile_Rule_C>
	<Ans_Call_Without_Reg_1_>Yes</Ans_Call_Without_Reg_1_>
	<Provision_Enable>Yes</Provision_Enable>
	<Message_Waiting_1_>No</Message_Waiting_1_>
	<Softswitch_Features></Softswitch_Features>
	<FAX_Process_NSE_1_>No</FAX_Process_NSE_1_>
	<SIT3_RSC></SIT3_RSC>
	<SAS_Enable_2_>No</SAS_Enable_2_>
	<Ring5_Cadence>1(.5/.5)</Ring5_Cadence>
	<CID_Serv_2_>Yes</CID_Serv_2_>
	<Proxy_2_>bks.tv</Proxy_2_>
	<CID_Act_Code></CID_Act_Code>
	<Call_Return_Serv_1_>No</Call_Return_Serv_1_>
	<Ring6_Cadence>60(.2/.4,.2/.4,.2/4)</Ring6_Cadence>
	<Media_Loopback_Mode_2_>Source</Media_Loopback_Mode_2_>
	<Upgrade_Rule>http://fw.voip/fw/\$PN/latest.bin</Upgrade_Rule>
	<Cblk_Ring_Splash_Len_1_>0</Cblk_Ring_Splash_Len_1_>
	<Cfwd_No_Ans_Dest_1_></Cfwd_No_Ans_Dest_1_>
	<Cfwd_Sel_Serv_2_>No</Cfwd_Sel_Serv_2_>
	<Outbound_Proxy_2_>bks.tv</Outbound_Proxy_2_>
	<FXS_Port_Input_Gain>0</FXS_Port_Input_Gain>
	<INFOREQ_Dynamic_Payload></INFOREQ_Dynamic_Payload>
	<G726r24_Codec_Name>G726-24</G726r24_Codec_Name>
	<Cfwd_Last_Dest_2_></Cfwd_Last_Dest_2_>
	<Prefer_G726r24_Code></Prefer_G726r24_Code>
	<CW_Deact_Code></CW_Deact_Code>
	<Speed_Dial_9_1_></Speed_Dial_9_1_>
	<Modem_Line_Toggle_Code></Modem_Line_Toggle_Code>
	<SAS_Inbound_RTP_Sink_2_></SAS_Inbound_RTP_Sink_2_>
	<Force_G726r16_Code></Force_G726r16_Code>
	<Block_Last_Act_Code></Block_Last_Act_Code>
	<Log_Upgrade_Failure_Msg>\$PN \$MAC -- Upgrade failed: \$ERR</Log_Upgrade_Failure_Msg>
	<Force_G723_Code></Force_G723_Code>
	<DTMF_Playback_Level>-16</DTMF_Playback_Level>
	<Ring4_Caller_2_></Ring4_Caller_2_>
	<RTP_Log_Intvl_2_>0</RTP_Log_Intvl_2_>
	<Three_Way_Call_Serv_1_>Yes</Three_Way_Call_Serv_1_>
	<Cfwd_Busy_Dest_2_></Cfwd_Busy_Dest_2_>
	<G711a_Codec_Name>PCMA</G711a_Codec_Name>
	<Cfwd_Sel8_Dest_1_></Cfwd_Sel8_Dest_1_>
	<Accept_Media_Loopback_Request_1_>Automatic</Accept_Media_Loopback_Request_1_>
	<Confirm_Tone>600@-16;1(.5/.5/1)</Confirm_Tone>
	<Call_Back_Retry_Intvl>30</Call_Back_Retry_Intvl>
	<Ring2_Caller_1_></Ring2_Caller_1_>
	<FAX_CED_Detect_Enable_1_>No</FAX_CED_Detect_Enable_1_>
	<Line_Enable_2_>Yes</Line_Enable_2_>
	<RFC_2543_Call_Hold>Yes</RFC_2543_Call_Hold>
	<Block_Last_Serv_2_>No</Block_Last_Serv_2_>
	<Set_Local_Time__HH_mm_></Set_Local_Time__HH_mm_>
	<SIP_Proxy-Require_1_></SIP_Proxy-Require_1_>
	<Use_Auth_ID_2_>Yes</Use_Auth_ID_2_>
	<Call_Back_Deact_Code></Call_Back_Deact_Code>
	<Admin_Passwd>gfgldfn</Admin_Passwd>
	<Web_Server_Port>80</Web_Server_Port>
	<Callee_On_Hook_Delay>0</Callee_On_Hook_Delay>
	<Ring7_Caller_1_></Ring7_Caller_1_>
	<Cfwd_Sel5_Dest_1_></Cfwd_Sel5_Dest_1_>
	<Ring2_Cadence>60(.8/.4,.8/4)</Ring2_Cadence>
	<G729b_Dynamic_Payload>99</G729b_Dynamic_Payload>
	<Speed_Dial_5_2_></Speed_Dial_5_2_>
	<Proxy_1_>bks.tv</Proxy_1_>
	<DNS_Query_Mode>Sequential</DNS_Query_Mode>
	<VMWI_Ring_Policy_1_>New VM Available</VMWI_Ring_Policy_1_>
	<CWT7_Cadence>30(.3/.1,.3/.1,.1/9.1)</CWT7_Cadence>
	<NetMask></NetMask>
	<Cfwd_No_Ans_Deact_Code></Cfwd_No_Ans_Deact_Code>
	<SAS_DLG_Refresh_Intvl_1_>30</SAS_DLG_Refresh_Intvl_1_>
	<NSE_Codec_Name>NSE</NSE_Codec_Name>
	<Refer-To_Target_Contact_1_>No</Refer-To_Target_Contact_1_>
	<SIP_100REL_Enable_2_>No</SIP_100REL_Enable_2_>
	<GPP_E></GPP_E>
	<Caller_Conn_Polarity_2_>Forward</Caller_Conn_Polarity_2_>
	<Block_CID_Per_Call_Act_Code></Block_CID_Per_Call_Act_Code>
	<Upgrade_Enable>Yes</Upgrade_Enable>
	<Cfwd_Ring_Splash_Len_1_>0</Cfwd_Ring_Splash_Len_1_>
	<RTP-Start-Loopback_Codec>G711a</RTP-Start-Loopback_Codec>
	<SIP_Debug_Option_2_>1-line excl. OPT|NTFY|REG</SIP_Debug_Option_2_>
	<Dial_Tone>420@-19;10(*/0/1)</Dial_Tone>
	<Force_G726r40_Code></Force_G726r40_Code>
	<Feature_Dial_Serv_1_>No</Feature_Dial_Serv_1_>
	<Use_Compact_Header>No</Use_Compact_Header>
	<Display_Name_2_>595001</Display_Name_2_>
	<Use_Pref_Codec_Only_1_>Yes</Use_Pref_Codec_Only_1_>
	<Auth_INVITE_1_>No</Auth_INVITE_1_>
	<Register_Expires_1_>43200</Register_Expires_1_>
	<Log_Resync_Success_Msg>\$PN \$MAC -- Successful resync \$SCHEME://\$SERVIP:\$PORT\$PATH</Log_Resync_Success_Msg>
	<Retry_Reg_RSC></Retry_Reg_RSC>
	<AVT_Codec_Name>telephone-event</AVT_Codec_Name>
	<Jitter_Buffer_Adjustment_2_>up only</Jitter_Buffer_Adjustment_2_>
	<Set_Local_Date__mm_dd_></Set_Local_Date__mm_dd_>
	<Speed_Dial_4_2_></Speed_Dial_4_2_>
	<Cfwd_No_Ans_Delay_1_></Cfwd_No_Ans_Delay_1_>
	<Static_IP></Static_IP>
	<Auth_ID_1_>%Auth_ID_1_%</Auth_ID_1_>
	<Cfwd_Sel5_Caller_2_></Cfwd_Sel5_Caller_2_>
	<Cfwd_Sel6_Dest_1_></Cfwd_Sel6_Dest_1_>
	<FAX_CNG_Detect_Enable_1_>No</FAX_CNG_Detect_Enable_1_>
	<Ring3_Caller_2_></Ring3_Caller_2_>
	<Resync_Trigger_2></Resync_Trigger_2>
	<Resync_Trigger_1></Resync_Trigger_1>
	<HostName></HostName>
	<DND_Dial_Tone>350@-19,440@-19;2(.2/.2/2);10(*/0/1+2)</DND_Dial_Tone>
	<DTMF_Process_AVT_2_>Yes</DTMF_Process_AVT_2_>
	<Mini_Certificate_1_></Mini_Certificate_1_>
	<Handle_VIA_received>No</Handle_VIA_received>
	<NAT_Mapping_Enable_2_>Yes</NAT_Mapping_Enable_2_>
	<CID_Deact_Code></CID_Deact_Code>
	<Prefer_G726r16_Code></Prefer_G726r16_Code>
	<Cfwd_Last_Act_Code></Cfwd_Last_Act_Code>
	<EXT_RTP_Port_Min></EXT_RTP_Port_Min>
	<DTMF_Tx_Method_2_>INFO</DTMF_Tx_Method_2_>
	<Cfwd_Sel5_Dest_2_></Cfwd_Sel5_Dest_2_>
	<STUN_Server></STUN_Server>
	<MWI_Serv_2_>No</MWI_Serv_2_>
	<Accept_Last_Serv_2_>No</Accept_Last_Serv_2_>
	<VMWI_Serv_1_>No</VMWI_Serv_1_>
	<Reg_Retry_Long_Intvl>60</Reg_Retry_Long_Intvl>
	<G729a_Codec_Name>G729a</G729a_Codec_Name>
	<User_Password>ntktajyysq</User_Password>
	<Emergency_Number_2_>01</Emergency_Number_2_>
	<Report_Rule></Report_Rule>
	<SIP_Timer_F>32</SIP_Timer_F>
	<SIT3_Tone>914@-16,1371@-16,1777@-16;20(.380/0/1,.380/0/2,.380/0/3,0/4/0)</SIT3_Tone>
	<NAT_Keep_Alive_Dest_2_>\$PROXY</NAT_Keep_Alive_Dest_2_>
	<Make_Call_Without_Reg_1_>No</Make_Call_Without_Reg_1_>
	<Silence_Supp_Enable_2_>no</Silence_Supp_Enable_2_>
	<SIP_Timer_H>32</SIP_Timer_H>
	<Dist_Ring_Deact_Code></Dist_Ring_Deact_Code>
	<Cfwd_Last_Caller_2_></Cfwd_Last_Caller_2_>
	<G726r24_Dynamic_Payload>97</G726r24_Dynamic_Payload>
	<Secure_Call_Serv_2_>No</Secure_Call_Serv_2_>
	<Cfwd_Sel6_Caller_1_></Cfwd_Sel6_Caller_1_>
	<Cfwd_All_Deact_Code></Cfwd_All_Deact_Code>
	<Hook_Flash_MIME_Type>application/hook-flash</Hook_Flash_MIME_Type>
	<Line_Enable_1_>Yes</Line_Enable_1_>
	<Callee_Conn_Polarity_1_>Forward</Callee_Conn_Polarity_1_>
	<CW_Setting_1_>Yes</CW_Setting_1_>
	<DND_Activated_1_>No</DND_Activated_1_>
	<CWT1_Cadence>30(.3/9.7)</CWT1_Cadence>
	<SIP_Timer_D>32</SIP_Timer_D>
	<CWT3_Cadence>30(.1/.1, .1/.1, .1/9.7)</CWT3_Cadence>
	<Accept_Last_Caller_1_></Accept_Last_Caller_1_>
	<Cfwd_Sel1_Caller_1_></Cfwd_Sel1_Caller_1_>
	<Call_Back_Ring_1_>7</Call_Back_Ring_1_>
	<Protect_IVR_FactoryReset>Yes</Protect_IVR_FactoryReset>
	<INVITE_Expires>240</INVITE_Expires>
	<Enable_Web_Server>Yes</Enable_Web_Server>
	<FXS_Port_Impedance>600</FXS_Port_Impedance>
	<Echo_Canc_Adapt_Enable_2_>Yes</Echo_Canc_Adapt_Enable_2_>
	<Cfwd_Busy_Serv_1_>No</Cfwd_Busy_Serv_1_>
	<Ring4_Cadence>60(.3/.2,1/.2,.3/4)</Ring4_Cadence>
	<Mark_All_AVT_Packets>Yes</Mark_All_AVT_Packets>
	<Display_Name_1_>595051</Display_Name_1_>
	<Cblk_Ring_Splash_Len_2_>0</Cblk_Ring_Splash_Len_2_>
	<Auth_MWI_2_>No</Auth_MWI_2_>
	<G729b_Codec_Name>G729ab</G729b_Codec_Name>
	<Media_Loopback_Mode_1_>Source</Media_Loopback_Mode_1_>
	<Service_Annc_Base_Number></Service_Annc_Base_Number>
	<G726-40_Enable_2_>No</G726-40_Enable_2_>
	<SAS_Enable_1_>No</SAS_Enable_1_>
	<Auth_Resync_2_>Yes</Auth_Resync_2_>
	<RTP_TOS_DiffServ_Value_1_>0xb8</RTP_TOS_DiffServ_Value_1_>
	<Cfwd_Sel3_Dest_1_></Cfwd_Sel3_Dest_1_>
	<Default_CWT_2_>1</Default_CWT_2_>
	<G726-16_Enable_2_>No</G726-16_Enable_2_>
	<Feature_Invocation_Method>Default</Feature_Invocation_Method>
	<Cfwd_Sel_Serv_1_>No</Cfwd_Sel_Serv_1_>
	<SAS_Inbound_RTP_Sink_1_></SAS_Inbound_RTP_Sink_1_>
	<STUN_Enable>No</STUN_Enable>
	<Max_RTP_ICMP_Err>0</Max_RTP_ICMP_Err>
	<Max_Auth>2</Max_Auth>
	<Block_ANC_Serv_2_>No</Block_ANC_Serv_2_>
	<Profile_Rule_B>https://$ENV{SERVER_NAME}:$ENV{SERVER_PORT}/provision.cgi?PN=\$PN&amp;MAU=\$MAU&amp;SN=\$SN</Profile_Rule_B>
	<Cfwd_Last_Dest_1_></Cfwd_Last_Dest_1_>
	<Speed_Dial_5_1_></Speed_Dial_5_1_>
	<Profile_Rule_D></Profile_Rule_D>
	<CW_Per_Call_Act_Code></CW_Per_Call_Act_Code>
	<Cfwd_Sel8_Caller_1_></Cfwd_Sel8_Caller_1_>
	<Secure_Call_Indication_Tone>397@-19,507@-19;15(0/2/0,.2/.1/1,.1/2.1/2)</Secure_Call_Indication_Tone>
	<SIP_TOS_DiffServ_Value_2_>0x68</SIP_TOS_DiffServ_Value_2_>
	<Prefer_G726r32_Code></Prefer_G726r32_Code>
	<Ring4_Caller_1_></Ring4_Caller_1_>
	<Call_Back_Ring_2_>7</Call_Back_Ring_2_>
	<Cfwd_All_Serv_1_>No</Cfwd_All_Serv_1_>
	<Echo_Supp_Enable_2_>Yes</Echo_Supp_Enable_2_>
	<G726-24_Enable_1_>No</G726-24_Enable_1_>
	<Attn-Xfer_Act_Code></Attn-Xfer_Act_Code>
	<EXT_IP></EXT_IP>
	<Ring_Frequency>25</Ring_Frequency>
	<Enable_IP_Dialing_2_>No</Enable_IP_Dialing_2_>
	<Reg_Retry_Random_Delay></Reg_Retry_Random_Delay>
	<Cfwd_No_Ans_Serv_2_>No</Cfwd_No_Ans_Serv_2_>
	<Reorder_Tone>420@-19;10(.4/.4/1)</Reorder_Tone>
	<RTP-Start-Loopback_Dynamic_Payload>113</RTP-Start-Loopback_Dynamic_Payload>
	<CWT4_Cadence>30(.1/.1,.3/.1,.1/9.3)</CWT4_Cadence>
	<Downgrade_Rev_Limit></Downgrade_Rev_Limit>
	<VMWI_Ring_Splash_Len_2_>0</VMWI_Ring_Splash_Len_2_>
	<User_ID_1_>595051</User_ID_1_>
	<SIP_Port_1_>5070</SIP_Port_1_>
	<Make_Call_Without_Reg_2_>No</Make_Call_Without_Reg_2_>
	<Cfwd_Sel6_Caller_2_></Cfwd_Sel6_Caller_2_>
	<Block_CID_Per_Call_Deact_Code></Block_CID_Per_Call_Deact_Code>
	<SIP_GUID_1_>No</SIP_GUID_1_>
	<MWI_Serv_1_>No</MWI_Serv_1_>
	<Ring1_Caller_1_></Ring1_Caller_1_>
	<Block_CID_Setting_1_>No</Block_CID_Setting_1_>
	<FAX_Disable_ECAN_2_>No</FAX_Disable_ECAN_2_>
	<NAT_Keep_Alive_Dest_1_>\$PROXY</NAT_Keep_Alive_Dest_1_>
	<Accept_Last_Caller_2_></Accept_Last_Caller_2_>
	<CW_Setting_2_>Yes</CW_Setting_2_>
	<Ring3_Name>Bellcore-r3</Ring3_Name>
	<Use_Auth_ID_1_>Yes</Use_Auth_ID_1_>
	<Hold_Reminder_Ring_1_>8</Hold_Reminder_Ring_1_>
	<VMWI_Ring_Splash_Len_1_>0</VMWI_Ring_Splash_Len_1_>
	<Substitute_VIA_Addr>No</Substitute_VIA_Addr>
	<SIP_Debug_Option_1_>1-line excl. OPT|NTFY|REG</SIP_Debug_Option_1_>
	<Idle_Polarity_1_>Forward</Idle_Polarity_1_>
	<G726-40_Enable_1_>No</G726-40_Enable_1_>
	<Three_Way_Conf_Serv_1_>Yes</Three_Way_Conf_Serv_1_>
	<Default_Ring_2_>1</Default_Ring_2_>
	<Speed_Dial_6_1_></Speed_Dial_6_1_>
	<Cfwd_Ring_Splash_Len_2_>0</Cfwd_Ring_Splash_Len_2_>
	<More_Echo_Suppression>Yes</More_Echo_Suppression>
	<SIT1_Tone>985@-16,1428@-16,1777@-16;20(.380/0/1,.380/0/2,.380/0/3,0/4/0)</SIT1_Tone>
	<NAT_Keep_Alive_Enable_1_>Yes</NAT_Keep_Alive_Enable_1_>
	<Block_Last_Caller_1_></Block_Last_Caller_1_>
	<Ring8_Caller_2_></Ring8_Caller_2_>
	<Ans_Call_Without_Reg_2_>Yes</Ans_Call_Without_Reg_2_>
	<Hook_Flash_Timer_Min>.1</Hook_Flash_Timer_Min>
	<CWT_Frequency>440@-10</CWT_Frequency>
	<Ring6_Name>Bellcore-r6</Ring6_Name>
	<Sticky_183_2_>No</Sticky_183_2_>
	<DTMF_Tx_Mode_2_>Strict</DTMF_Tx_Mode_2_>
	<G726-32_Enable_2_>No</G726-32_Enable_2_>
	<SIP_Server_Name>\$VERSION</SIP_Server_Name>
	<Speed_Dial_2_1_></Speed_Dial_2_1_>
	<Echo_Supp_Enable_1_>Yes</Echo_Supp_Enable_1_>
	<MWI_Dial_Tone>350@-19,440@-19;2(.1/.1/1+2);10(*/0/1+2)</MWI_Dial_Tone>
	<Dist_Ring_Serv_2_>No</Dist_Ring_Serv_2_>
	<Resync_After_Upgrade_Attempt>Yes</Resync_After_Upgrade_Attempt>
	<Enable_Web_Admin_Access>Yes</Enable_Web_Admin_Access>
	<Voice_Mail_Server_1_></Voice_Mail_Server_1_>
	<Busy_Tone>420@-19;10(.5/.5/1)</Busy_Tone>
	<SIP_User_Agent_Name>\$VERSION</SIP_User_Agent_Name>
	<NAT_Keep_Alive_Msg_1_>\$NOTIFY</NAT_Keep_Alive_Msg_1_>
	<Referee_Bye_Delay_1_>0</Referee_Bye_Delay_1_>
	<Enable_IP_Dialing_1_>No</Enable_IP_Dialing_1_>
	<Cfwd_No_Ans_Serv_1_>No</Cfwd_No_Ans_Serv_1_>
	<Block_Last_Caller_2_></Block_Last_Caller_2_>
	<Block_CID_Deact_Code></Block_CID_Deact_Code>
	<Cfwd_No_Ans_Delay_2_></Cfwd_No_Ans_Delay_2_>
	<Cfwd_Sel5_Caller_1_></Cfwd_Sel5_Caller_1_>
	<Secure_One_Call_Deact_Code></Secure_One_Call_Deact_Code>
	<Prefer_G726r40_Code></Prefer_G726r40_Code>
	<NAT_Mapping_Enable_1_>Yes</NAT_Mapping_Enable_1_>
	<Cfwd_All_Act_Code></Cfwd_All_Act_Code>
	<G729a_Enable_2_>No</G729a_Enable_2_>
	<Resync_Random_Delay>151200</Resync_Random_Delay>
	<DTMF_Playback_Length>.1</DTMF_Playback_Length>
	<Auth_Resync_1_>Yes</Auth_Resync_1_>
	<Speed_Dial_9_2_></Speed_Dial_9_2_>
	<Secondary_NTP_Server>77.232.135.1</Secondary_NTP_Server>
	<DTMF_Tx_Method_1_>INFO</DTMF_Tx_Method_1_>
	<Prefer_G711u_Code></Prefer_G711u_Code>
	<Accept_Last_Deact_Code></Accept_Last_Deact_Code>
	<Accept_Media_Loopback_Request_2_>Automatic</Accept_Media_Loopback_Request_2_>
	<Unattn_Transfer_Serv_1_>Yes</Unattn_Transfer_Serv_1_>
	<CWT6_Cadence>30(.1/.1,.3/.2,.3/9.1)</CWT6_Cadence>
	<Resync_Periodic>21600</Resync_Periodic>
	<Feature_Dial_Services_Codes></Feature_Dial_Services_Codes>
	<G726r40_Codec_Name>G726-40</G726r40_Codec_Name>
	<Blind_Transfer_Code></Blind_Transfer_Code>
	<Cfwd_All_Dest_1_></Cfwd_All_Dest_1_>
	<Register_1_>Yes</Register_1_>
	<Use_Outbound_Proxy_1_>Yes</Use_Outbound_Proxy_1_>
	<Secure_Call_Setting_1_>No</Secure_Call_Setting_1_>
	<Xfer_When_Hangup_Conf_2_>No</Xfer_When_Hangup_Conf_2_>
	<SIP_Timer_J>32</SIP_Timer_J>
	<Accept_Last_Serv_1_>No</Accept_Last_Serv_1_>
	<Silence_Supp_Enable_1_>no</Silence_Supp_Enable_1_>
	<Proxy_Fallback_Intvl_1_>5</Proxy_Fallback_Intvl_1_>
	<CWT2_Cadence>30(.1/.1, .1/9.7)</CWT2_Cadence>
	<Ring8_Cadence>60(0.25/9.75)</Ring8_Cadence>
	<Speed_Dial_Serv_1_>No</Speed_Dial_Serv_1_>
	<Ring2_Caller_2_></Ring2_Caller_2_>
	<GPP_C></GPP_C>
	<GPP_B></GPP_B>
	<GPP_A></GPP_A>
	<GPP_G></GPP_G>
	<GPP_F></GPP_F>
	<Echo_Canc_Adapt_Enable_1_>Yes</Echo_Canc_Adapt_Enable_1_>
	<GPP_D></GPP_D>
	<GPP_K></GPP_K>
	<GPP_J></GPP_J>
	<GPP_I></GPP_I>
	<GPP_H></GPP_H>
	<GPP_O></GPP_O>
	<GPP_N></GPP_N>
	<GPP_M></GPP_M>
	<GPP_L></GPP_L>
	<SAS_DLG_Refresh_Intvl_2_>30</SAS_DLG_Refresh_Intvl_2_>
	<Max_Redirection>5</Max_Redirection>
	<GPP_P></GPP_P>
	<Ring7_Caller_2_></Ring7_Caller_2_>
	<Cfwd_Sel2_Dest_2_></Cfwd_Sel2_Dest_2_>
	<Conference_Tone>350@-19;20(.1/.1/1,.1/9.7/1)</Conference_Tone>
	<Call_Back_Serv_1_>No</Call_Back_Serv_1_>
	<G726-16_Enable_1_>No</G726-16_Enable_1_>
	<Cfwd_Last_Serv_2_>No</Cfwd_Last_Serv_2_>
	<Attn_Transfer_Serv_1_>Yes</Attn_Transfer_Serv_1_>
	<Force_G729a_Code></Force_G729a_Code>
	<Default_Ring_1_>1</Default_Ring_1_>
	<Reg_Min_Expires>600</Reg_Min_Expires>
	<RTP_TOS_DiffServ_Value_2_>0xb8</RTP_TOS_DiffServ_Value_2_>
	<Release_Unused_Codec_1_>Yes</Release_Unused_Codec_1_>
	<Mailbox_Subscribe_Expires_2_>2147483647</Mailbox_Subscribe_Expires_2_>
	<Default_CWT_1_>1</Default_CWT_1_>
	<CW_Act_Code></CW_Act_Code>
	<Try_Backup_RSC></Try_Backup_RSC>
	<Hook_Flash_Tx_Method_1_>INFO</Hook_Flash_Tx_Method_1_>
	<Force_G711u_Code></Force_G711u_Code>
	<GPP_SA></GPP_SA>
	<GPP_SC></GPP_SC>
	<GPP_SB></GPP_SB>
	<GPP_SD></GPP_SD>
	<Speed_Dial_7_2_></Speed_Dial_7_2_>
	<CID_Setting_1_>Yes</CID_Setting_1_>
	<DTMF_Process_INFO_2_>Yes</DTMF_Process_INFO_2_>
	<SIT1_RSC></SIT1_RSC>
	<Resync_Error_Retry_Delay>300</Resync_Error_Retry_Delay>
	<G729a_Enable_1_>No</G729a_Enable_1_>
	<Upgrade_Error_Retry_Delay>3600</Upgrade_Error_Retry_Delay>
	<Detect_ABCD>Yes</Detect_ABCD>
	<Referral_Serv_2_>No</Referral_Serv_2_>
	<Conference_Bridge_Ports_1_>3</Conference_Bridge_Ports_1_>
	<Cfwd_All_Serv_2_>No</Cfwd_All_Serv_2_>
	<G726-24_Enable_2_>No</G726-24_Enable_2_>
	<Block_CID_Serv_1_>No</Block_CID_Serv_1_>
	<Insert_VIA_rport>No</Insert_VIA_rport>
	<Cfwd_Sel8_Caller_2_></Cfwd_Sel8_Caller_2_>
	<Call_Return_Code></Call_Return_Code>
	<CPC_Delay>2</CPC_Delay>
	<Message_Waiting_2_>No</Message_Waiting_2_>
	<Cfwd_Sel7_Caller_2_></Cfwd_Sel7_Caller_2_>
	<Silence_Threshold_1_>low</Silence_Threshold_1_>
	<FAX_Codec_Symmetric_2_>Yes</FAX_Codec_Symmetric_2_>
	<Ring7_Cadence>60(.4/.2,.4/.2,.4/4)</Ring7_Cadence>
	<Debug_Server>172.17.1.1</Debug_Server>
	<Insert_VIA_received>No</Insert_VIA_received>
	<Ring1_Cadence>60(2/4)</Ring1_Cadence>
	<Block_CID_Setting_2_>No</Block_CID_Setting_2_>
	<User_ID_2_>595001</User_ID_2_>
	<EXT_SIP_Port_2_></EXT_SIP_Port_2_>
	<DNS_Server_Order>Manual,DHCP</DNS_Server_Order>
	<Secure_All_Call_Act_Code></Secure_All_Call_Act_Code>
	<Ring1_Caller_2_></Ring1_Caller_2_>
	<Mini_Certificate_2_></Mini_Certificate_2_>
	<Log_Upgrade_Success_Msg>\$PN \$MAC -- Successful upgrade \$SCHEME://\$SERVIP:\$PORT\$PATH -- \$ERR</Log_Upgrade_Success_Msg>
	<Refer-To_Target_Contact_2_>No</Refer-To_Target_Contact_2_>
	<NSE_Dynamic_Payload>100</NSE_Dynamic_Payload>
	<DND_Deact_Code></DND_Deact_Code>
	<Remove_Last_Reg>No</Remove_Last_Reg>
	<Secure_No_Call_Act_Code></Secure_No_Call_Act_Code>
	<Use_OB_Proxy_In_Dialog_1_>Yes</Use_OB_Proxy_In_Dialog_1_>
	<Silence_Threshold_2_>low</Silence_Threshold_2_>
	<Call_Waiting_Serv_2_>No</Call_Waiting_Serv_2_>
	<CWCID_Deact_Code></CWCID_Deact_Code>
	<Service_Announcement_Serv_1_>No</Service_Announcement_Serv_1_>
	<Prefer_G723_Code></Prefer_G723_Code>
	<SRTP_Private_Key_1_></SRTP_Private_Key_1_>
	<Idle_Polarity_2_>Forward</Idle_Polarity_2_>
	<Block_CID_Act_Code></Block_CID_Act_Code>
	<Cfwd_Sel7_Dest_1_></Cfwd_Sel7_Dest_1_>
	<Refer_Target_Bye_Delay_1_>0</Refer_Target_Bye_Delay_1_>
	<Cfwd_Sel4_Caller_1_></Cfwd_Sel4_Caller_1_>
	<Release_Unused_Codec_2_>Yes</Release_Unused_Codec_2_>
	<SIP_Remote-Party-ID_2_>Yes</SIP_Remote-Party-ID_2_>
	<Referor_Bye_Delay_2_>1</Referor_Bye_Delay_2_>
	<Secondary_DNS>77.232.135.1</Secondary_DNS>
	<Mailbox_Subscribe_Expires_1_>2147483647</Mailbox_Subscribe_Expires_1_>
	<Cfwd_Last_Serv_1_>No</Cfwd_Last_Serv_1_>
	<NAT_Keep_Alive_Enable_2_>Yes</NAT_Keep_Alive_Enable_2_>
	<Hook_Flash_Tx_Method_2_>INFO</Hook_Flash_Tx_Method_2_>
	<DTMF_Relay_MIME_Type>application/dtmf-relay</DTMF_Relay_MIME_Type>
	<Ring4_Name>Bellcore-r4</Ring4_Name>
	<Cfwd_Dial_Tone>350@-19,440@-19;2(.2/.2/1+2);10(*/0/1+2)</Cfwd_Dial_Tone>
	<FXS_Port_Power_Limit>3</FXS_Port_Power_Limit>
	<Synchronized_Ring>Yes</Synchronized_Ring>
	<Dist_Ring_Act_Code></Dist_Ring_Act_Code>
	<Playback_ABCD>Yes</Playback_ABCD>
	<Dist_Ring_Serv_1_>No</Dist_Ring_Serv_1_>
	<Ring_Waveform>Sinusoid</Ring_Waveform>
	<Ring1_Name>Bellcore-r1</Ring1_Name>
	<Cfwd_No_Ans_Act_Code></Cfwd_No_Ans_Act_Code>
	<No_UDP_Checksum>0</No_UDP_Checksum>
	<Cfwd_Busy_Serv_2_>No</Cfwd_Busy_Serv_2_>
	<Auth_MWI_1_>No</Auth_MWI_1_>
	<Cfwd_Sel4_Dest_2_></Cfwd_Sel4_Dest_2_>
	<Cfwd_Sel3_Dest_2_></Cfwd_Sel3_Dest_2_>
	<Max_Forward>70</Max_Forward>
	<Service_Announcement_Serv_2_>No</Service_Announcement_Serv_2_>
	<Block_ANC_Deact_Code></Block_ANC_Deact_Code>
	<DHCP>Yes</DHCP>
	<Password_1_>%Password_1_%</Password_1_>
        <CLID_>%Caller_ID_1_%</CLID_>
	<Stats_In_BYE>No</Stats_In_BYE>
	<DND_Serv_1_>No</DND_Serv_1_>
	<CWCID_Serv_1_>No</CWCID_Serv_1_>
	<CWT8_Cadence>2.3(.3/2)</CWT8_Cadence>
	<Use_Pref_Codec_Only_2_>Yes</Use_Pref_Codec_Only_2_>
	<DNS_SRV_Auto_Prefix_2_>Yes</DNS_SRV_Auto_Prefix_2_>
	<Force_G726r24_Code></Force_G726r24_Code>
	<Sticky_183_1_>No</Sticky_183_1_>
	<Reorder_Delay>5</Reorder_Delay>
	<Reg_Max_Expires>86400</Reg_Max_Expires>
	<G723_Codec_Name>G723</G723_Codec_Name>
	<Attn_Transfer_Serv_2_>Yes</Attn_Transfer_Serv_2_>
	<Secure_Call_Setting_2_>No</Secure_Call_Setting_2_>
	<Register_2_>Yes</Register_2_>
	<G723_Enable_2_>No</G723_Enable_2_>
	<G711u_Codec_Name>PCMU</G711u_Codec_Name>
	<EncapRTP_Dynamic_Payload>112</EncapRTP_Dynamic_Payload>
	<Caller_ID_FSK_Standard>bell 202</Caller_ID_FSK_Standard>
	<FAX_Disable_ECAN_1_>No</FAX_Disable_ECAN_1_>
	<FAX_Passthru_Method_2_>None</FAX_Passthru_Method_2_>
	<NAT_Keep_Alive_Intvl>5</NAT_Keep_Alive_Intvl>
	<Ring8_Name>Bellcore-r8</Ring8_Name>
	<SIP_Accept_Language></SIP_Accept_Language>
	<Dial_Plan_2_>(375x. | S0 8,1[89]1| 0[1-39]|S0 0[67]x|S0 [2-79]xxxxx|S2 8,xxxxxxxxxx|S4 8,10x. | 00x.)</Dial_Plan_2_>
	<Hold_Reminder_Ring_2_>8</Hold_Reminder_Ring_2_>
	<Blind_Attn-Xfer_Enable_1_>No</Blind_Attn-Xfer_Enable_1_>
	<Speed_Dial_6_2_></Speed_Dial_6_2_>
	<CW_Per_Call_Deact_Code></CW_Per_Call_Deact_Code>
	<Cfwd_No_Ans_Dest_2_></Cfwd_No_Ans_Dest_2_>
	<Preferred_Codec_2_>G711a</Preferred_Codec_2_>
	<Speed_Dial_8_1_></Speed_Dial_8_1_>
	<Secure_Call_Serv_1_>No</Secure_Call_Serv_1_>
	<SIP_Timer_B>32</SIP_Timer_B>
	<G726r16_Codec_Name>G726-16</G726r16_Codec_Name>
	<Ring8_Caller_1_></Ring8_Caller_1_>
	<Send_Resp_To_Src_Port>No</Send_Resp_To_Src_Port>
	<Cfwd_Sel2_Dest_1_></Cfwd_Sel2_Dest_1_>
	<Cfwd_Sel4_Dest_1_></Cfwd_Sel4_Dest_1_>
	<Proxy_Redundancy_Method_1_>Based on SRV Port</Proxy_Redundancy_Method_1_>
	<Call_Back_Serv_2_>No</Call_Back_Serv_2_>
	<Use_DNS_SRV_2_>Yes</Use_DNS_SRV_2_>
	<Cfwd_Sel1_Dest_1_></Cfwd_Sel1_Dest_1_>
	<SIP_GUID_2_>No</SIP_GUID_2_>
	<Unattn_Transfer_Serv_2_>Yes</Unattn_Transfer_Serv_2_>
	<CWCID_Setting_1_>Yes</CWCID_Setting_1_>
	<Service_Annc_Extension_Codes></Service_Annc_Extension_Codes>
	<DND_Setting_1_>No</DND_Setting_1_>
	<Password_2_>%Password_2_%</Password_2_>
	<Network_Jitter_Level_2_>high</Network_Jitter_Level_2_>
	<Reg_Retry_Intvl>60</Reg_Retry_Intvl>
	<Ring_On_No_New_VM_1_>Yes</Ring_On_No_New_VM_1_>
	<G726-32_Enable_1_>No</G726-32_Enable_1_>
	<Reg_Retry_Long_Random_Delay></Reg_Retry_Long_Random_Delay>
	<G726r32_Codec_Name>G726-32</G726r32_Codec_Name>
	<Call_Back_Expires>1000</Call_Back_Expires>
	<Call_Back_Act_Code></Call_Back_Act_Code>
	<Referral_Services_Codes></Referral_Services_Codes>
	<Preferred_Codec_1_>G711a</Preferred_Codec_1_>
	<Speed_Dial_7_1_></Speed_Dial_7_1_>
	<Accept_Last_Act_Code></Accept_Last_Act_Code>
	<Conference_Bridge_Ports_2_>3</Conference_Bridge_Ports_2_>
	<Resync_On_Reset>Yes</Resync_On_Reset>
	<Resync_Fails_On_FNF>No</Resync_Fails_On_FNF>
	<Referee_Bye_Delay_2_>0</Referee_Bye_Delay_2_>
	<Escape_Display_Name>No</Escape_Display_Name>
	<Ring6_Caller_2_></Ring6_Caller_2_>
	<Three_Way_Conf_Serv_2_>Yes</Three_Way_Conf_Serv_2_>
	<Speed_Dial_2_2_></Speed_Dial_2_2_>
	<RTP_Port_Min>16384</RTP_Port_Min>
	<Cfwd_Sel7_Caller_1_></Cfwd_Sel7_Caller_1_>
	<FAX_Passthru_Method_1_>None</FAX_Passthru_Method_1_>
	<Cfwd_Sel2_Caller_1_></Cfwd_Sel2_Caller_1_>
	<G726r40_Dynamic_Payload>96</G726r40_Dynamic_Payload>
	<Speed_Dial_Serv_2_>No</Speed_Dial_Serv_2_>
	<Dial_Plan_1_>(375x. | S0 8,1[89]1| 0[1-39]|S0 0[67]x|S0 [2-79]xxxxx|S2 8,xxxxxxxxxx|S4 8,10x. | 00x.)</Dial_Plan_1_>
	<AVT_Dynamic_Payload>101</AVT_Dynamic_Payload>
	<SIT4_Tone>985@-16,1371@-16,1777@-16;20(.380/0/1,.274/0/2,.380/0/3,0/4/0)</SIT4_Tone>
	<SIT2_RSC></SIT2_RSC>
	<Speed_Dial_3_2_></Speed_Dial_3_2_>
	<FXS_Port_Output_Gain>0</FXS_Port_Output_Gain>
	<DND_Act_Code></DND_Act_Code>
	<Call_Waiting_Serv_1_>No</Call_Waiting_Serv_1_>
	<SIP_Remote-Party-ID_1_>Yes</SIP_Remote-Party-ID_1_>
	<Refer_Target_Bye_Delay_2_>0</Refer_Target_Bye_Delay_2_>
	<Referor_Bye_Delay_1_>1</Referor_Bye_Delay_1_>
	<Block_Last_Deact_Code></Block_Last_Deact_Code>
	<SRTP_Private_Key_2_></SRTP_Private_Key_2_>
	<Cfwd_All_Dest_2_></Cfwd_All_Dest_2_>
	<RTCP_Tx_Interval>0</RTCP_Tx_Interval>
	<Ring7_Name>Bellcore-r7</Ring7_Name>
	<MOH_Server_2_></MOH_Server_2_>
	<Conference_Bridge_URL_1_></Conference_Bridge_URL_1_>
	<G726r32_Dynamic_Payload>2</G726r32_Dynamic_Payload>
	<Domain>bks-tv.ru</Domain>
	<Proxy_Fallback_Intvl_2_>5</Proxy_Fallback_Intvl_2_>
	<Use_Outbound_Proxy_2_>Yes</Use_Outbound_Proxy_2_>
	<Ring5_Name>Bellcore-r5</Ring5_Name>
	<Ring5_Caller_1_></Ring5_Caller_1_>
	<Ring_Voltage>70</Ring_Voltage>
	<Echo_Canc_Enable_1_>Yes</Echo_Canc_Enable_1_>
	<Conference_Act_Code></Conference_Act_Code>
	<Log_Resync_Request_Msg>\$PN \$MAC -- Requesting resync \$SCHEME://\$SERVIP:\$PORT\$PATH</Log_Resync_Request_Msg>
	<Auth_INVITE_2_>No</Auth_INVITE_2_>
	<Call_Return_Serv_2_>No</Call_Return_Serv_2_>
	<EncapRTP_Codec_Name>encaprtp</EncapRTP_Codec_Name>
	<Feature_Invocation_Tone>350@-16;*(.1/.1/1)</Feature_Invocation_Tone>
	<Restrict_Source_IP_2_>No</Restrict_Source_IP_2_>
	<Syslog_Server>172.17.1.1</Syslog_Server>
	<Conference_Bridge_URL_2_></Conference_Bridge_URL_2_>
	<Call_Back_Delay>.5</Call_Back_Delay>
	<Block_ANC_Act_Code></Block_ANC_Act_Code>
	<DTMF_Tx_Mode_1_>Strict</DTMF_Tx_Mode_1_>
	<SIT4_RSC></SIT4_RSC>
	<CID_Serv_1_>Yes</CID_Serv_1_>
	<Block_Last_Serv_1_>No</Block_Last_Serv_1_>
	<Auth_ID_2_>%Auth_ID_2_%</Auth_ID_2_>
	<Ring3_Caller_1_></Ring3_Caller_1_>
	<FAX_CNG_Detect_Enable_2_>No</FAX_CNG_Detect_Enable_2_>
	<Cfwd_Sel6_Dest_2_></Cfwd_Sel6_Dest_2_>
	<CID_Setting_2_>Yes</CID_Setting_2_>
	<RTP_Log_Intvl_1_>0</RTP_Log_Intvl_1_>
	<Caller_Conn_Polarity_1_>Forward</Caller_Conn_Polarity_1_>
	<DTMF_Process_INFO_1_>Yes</DTMF_Process_INFO_1_>
	<Media_Loopback_Code></Media_Loopback_Code>
	<Media_Loopback_Type_1_>Media</Media_Loopback_Type_1_>
	<EXT_SIP_Port_1_></EXT_SIP_Port_1_>
	<FAX_Passthru_Codec_1_>G711a</FAX_Passthru_Codec_1_>
	<Block_CID_Serv_2_>No</Block_CID_Serv_2_>
	<Dist_Ring_Setting_2_>Yes</Dist_Ring_Setting_2_>
	<Log_Resync_Failure_Msg>\$PN \$MAC -- Resync failed: \$ERR</Log_Resync_Failure_Msg>
	<Three_Way_Call_Serv_2_>Yes</Three_Way_Call_Serv_2_>
	<Register_Expires_2_>43200</Register_Expires_2_>
	<Cfwd_Busy_Dest_1_></Cfwd_Busy_Dest_1_>
	<CWT5_Cadence>1(.5/.5)</CWT5_Cadence>
	<Referral_Serv_1_>No</Referral_Serv_1_>
	<FAX_Codec_Symmetric_1_>Yes</FAX_Codec_Symmetric_1_>
	<VMWI_Serv_2_>No</VMWI_Serv_2_>
	<Use_DNS_SRV_1_>Yes</Use_DNS_SRV_1_>
	<Cfwd_Last_Caller_1_></Cfwd_Last_Caller_1_>
	<RTP_Port_Max>16482</RTP_Port_Max>
	<SIP_T1>.5</SIP_T1>
	<Ring5_Caller_2_></Ring5_Caller_2_>
	<Off_Hook_Warning_Tone>480@-10;10(.125/.125/1)</Off_Hook_Warning_Tone>
	<Debug_Level>0</Debug_Level>
	<CPC_Duration>0</CPC_Duration>
	<FAX_CED_Detect_Enable_2_>No</FAX_CED_Detect_Enable_2_>
	<Resync_From_SIP>No</Resync_From_SIP>
	<FAX_Process_NSE_2_>No</FAX_Process_NSE_2_>
	<Cfwd_Sel1_Caller_2_></Cfwd_Sel1_Caller_2_>
	<Echo_Canc_Enable_2_>Yes</Echo_Canc_Enable_2_>
	<NAT_Keep_Alive_Msg_2_>\$NOTIFY</NAT_Keep_Alive_Msg_2_>
	<Prompt_Tone>520@-19;10(*/0/1)</Prompt_Tone>
	<Callee_Conn_Polarity_2_>Forward</Callee_Conn_Polarity_2_>
	<Blind_Attn-Xfer_Enable_2_>No</Blind_Attn-Xfer_Enable_2_>
	<Time_Zone>GMT+03:00</Time_Zone>
	<SIP_Proxy-Require_2_></SIP_Proxy-Require_2_>
	<Outside_Dial_Tone>420@-16;10(*/0/1)</Outside_Dial_Tone>
	<DTMF_Process_AVT_1_>Yes</DTMF_Process_AVT_1_>
	<DND_Activated_2_>No</DND_Activated_2_>
	<Cfwd_Sel3_Caller_2_></Cfwd_Sel3_Caller_2_>
	<Cfwd_Sel7_Dest_2_></Cfwd_Sel7_Dest_2_>
	<Ring3_Cadence>60(.4/.2,.4/.2,.8/4)</Ring3_Cadence>
	<DND_Setting_2_>No</DND_Setting_2_>
	<Cfwd_Sel4_Caller_2_></Cfwd_Sel4_Caller_2_>
	<CWCID_Act_Code></CWCID_Act_Code>
	<ReINVITE_Expires>30</ReINVITE_Expires>
	<CWCID_Setting_2_>Yes</CWCID_Setting_2_>
	<Speed_Dial_8_2_></Speed_Dial_8_2_>
	<Cfwd_Busy_Deact_Code></Cfwd_Busy_Deact_Code>
	<Use_OB_Proxy_In_Dialog_2_>Yes</Use_OB_Proxy_In_Dialog_2_>
	<RTP_Packet_Size>0.030</RTP_Packet_Size>
	<G726r16_Dynamic_Payload>98</G726r16_Dynamic_Payload>
	<Feature_Dial_Serv_2_>No</Feature_Dial_Serv_2_>
	<Block_ANC_Setting_1_>No</Block_ANC_Setting_1_>
	<Log_Upgrade_Request_Msg>\$PN \$MAC -- Requesting upgrade \$SCHEME://\$SERVIP:\$PORT\$PATH</Log_Upgrade_Request_Msg>
	<SIP_T4>5</SIP_T4>
	<Cfwd_Sel1_Dest_2_></Cfwd_Sel1_Dest_2_>
	<SIP_100REL_Enable_1_>No</SIP_100REL_Enable_1_>
	<SIP_T2>4</SIP_T2>
	<Holding_Tone>600@-19;*(.1/.1/1,.1/.1/1,.1/9.5/1)</Holding_Tone>
	<Emergency_Number_1_></Emergency_Number_1_>
	<Xfer_When_Hangup_Conf_1_>No</Xfer_When_Hangup_Conf_1_>
	<Network_Jitter_Level_1_>high</Network_Jitter_Level_1_>
	<Gateway></Gateway>
	<Cfwd_Busy_Act_Code></Cfwd_Busy_Act_Code>
</flat-profile>


