<TR bgcolor=$_COLORS[2]><TD>$_COUNTRY:</TD><TD>
<select name=country>
<option value=004> Afghanistan</option>
<option value=008> Albania</option>
<option value=010> Antarctica</option>
<option value=012> Algeria</option>
<option value=016> American Samoa</option>
<option value=031> Azerbaijan</option>
<option value=032> Argentina</option>
<option value=036> Australia</option>
<option value=040> Austria</option>
<option value=044> Bahamas</option>
<option value=048> Bahrain</option>
<option value=050> Bangladesh</option>
<option value=051> Armenia</option>
<option value=056> Belgium</option>
<option value=060> Bermuda</option>
<option value=064> Bhutan</option>
<option value=068> Bolivia, Plurinational State of</option>
<option value=070> Bosnia and Herzegovina</option>
<option value=072> Botswana</option>
<option value=074> Bouvet Island</option>
<option value=076> Brazil</option>
<option value=086> British Indian Ocean Territory</option>
<option value=090> Solomon Islands</option>
<option value=092> Virgin Islands, British</option>
<option value=096> Brunei Darussalam</option>
<option value=100> Bulgaria</option>
<option value=108> Burundi</option>
<option value=112> Belarus</option>
<option value=116> Cambodia</option>
<option value=120> Cameroon</option>
<option value=124> Canada</option>
<option value=132> Cape Verde</option>
<option value=136> Cayman Islands</option>
<option value=140> Central African Republic</option>
<option value=144> Sri Lanka</option>
<option value=148> Chad</option>
<option value=152> Chile</option>
<option value=156> China</option>
<option value=158> Taiwan, Province of China</option>
<option value=162> Christmas Island</option>
<option value=166> Cocos (Keeling) Islands</option>
<option value=170> Colombia</option>
<option value=174> Comoros</option>
<option value=175> Mayotte</option>
<option value=178> Congo</option>
<option value=180> Congo, the Democratic Republic of the</option>
<option value=184> Cook Islands</option>
<option value=188> Costa Rica</option>
<option value=191> Croatia</option>
<option value=192> Cuba</option>
<option value=196> Cyprus</option>
<option value=203> Czech Republic</option>
<option value=204> Benin</option>
<option value=208> Denmark</option>
<option value=212> Dominica</option>
<option value=214> Dominican Republic</option>
<option value=218> Ecuador</option>
<option value=222> El Salvador</option>
<option value=226> Equatorial Guinea</option>
<option value=231> Ethiopia</option>
<option value=232> Eritrea</option>
<option value=233> Estonia</option>
<option value=234> Faroe Islands</option>
<option value=238> Falkland Islands (Malvinas)</option>
<option value=239> South Georgia and the South Sandwich Islands</option>
<option value=246> Finland</option>
<option value=250> France</option>
<option value=254> French Guiana</option>
<option value=258> French Polynesia</option>
<option value=260> French Southern Territories</option>
<option value=262> Djibouti</option>
<option value=266> Gabon</option>
<option value=268> Georgia</option>
<option value=275> Palestinian Territory, Occupied</option>
<option value=276> Germany</option>
<option value=296> Kiribati</option>
<option value=300> Greece</option>
<option value=304> Greenland</option>
<option value=308> Grenada</option>
<option value=312> Guadeloupe</option>
<option value=332> Haiti</option>
<option value=334> Heard Island and McDonald Islands</option>
<option value=336> Holy See (Vatican City State)</option>
<option value=344> Hong Kong</option>
<option value=348> Hungary</option>
<option value=352> Iceland</option>
<option value=356> India</option>
<option value=360> Indonesia</option>
<option value=364> Iran, Islamic Republic of</option>
<option value=368> Iraq</option>
<option value=372> Ireland</option>
<option value=376> Israel</option>
<option value=380> Italy</option>
<option value=384> Cote d'Ivoire</option>
<option value=388> Jamaica</option>
<option value=392> Japan</option>
<option value=398> Kazakhstan</option>
<option value=408> Korea, Democratic People's Republic of</option>
<option value=410> Korea, Republic of</option>
<option value=414> Kuwait</option>
<option value=417> Kyrgyzstan</option>
<option value=418> Lao People's Democratic Republic</option>
<option value=422> Lebanon</option>
<option value=426> Lesotho</option>
<option value=428> Latvia</option>
<option value=430> Liberia</option>
<option value=442> Luxembourg</option>
<option value=446> Macao</option>
<option value=450> Madagascar</option>
<option value=454> Malawi</option>
<option value=458> Malaysia</option>
<option value=470> Malta</option>
<option value=474> Martinique</option>
<option value=478> Mauritania</option>
<option value=480> Mauritius</option>
<option value=484> Mexico</option>
<option value=492> Monaco</option>
<option value=496> Mongolia</option>
<option value=498> Moldova, Republic of</option>
<option value=512> Oman</option>
<option value=516> Namibia</option>
<option value=528> Netherlands</option>
<option value=530> Netherlands Antilles</option>
<option value=533> Aruba</option>
<option value=554> New Zealand</option>
<option value=574> Norfolk Island</option>
<option value=578> Norway</option>
<option value=580> Northern Mariana Islands</option>
<option value=581> United States Minor Outlying Islands</option>
<option value=583> Micronesia, Federated States of</option>
<option value=584> Marshall Islands</option>
<option value=585> Palau</option>
<option value=586> Pakistan</option>
<option value=591> Panama</option>
<option value=598> Papua New Guinea</option>
<option value=600> Paraguay</option>
<option value=604> Peru</option>
<option value=608> Philippines</option>
<option value=612> Pitcairn</option>
<option value=616> Poland</option>
<option value=620> Portugal</option>
<option value=624> Guinea-Bissau</option>
<option value=626> Timor-Leste</option>
<option value=630> Puerto Rico</option>
<option value=634> Qatar</option>
<option value=638> Reunion</option>
<option value=642> Romania</option>
<option value=643> Russian Federation</option>
<option value=682> Saudi Arabia</option>
<option value=686> Senegal</option>
<option value=688> Serbia</option>
<option value=690> Seychelles</option>
<option value=694> Sierra Leone</option>
<option value=702> Singapore</option>
<option value=703> Slovakia</option>
<option value=704> Viet Nam</option>
<option value=705> Slovenia</option>
<option value=706> Somalia</option>
<option value=710> South Africa</option>
<option value=716> Zimbabwe</option>
<option value=724> Spain</option>
<option value=732> Western Sahara</option>
<option value=736> Sudan</option>
<option value=740> Suriname</option>
<option value=744> Svalbard and Jan Mayen</option>
<option value=748> Swaziland</option>
<option value=752> Sweden</option>
<option value=756> Switzerland</option>
<option value=760> Syrian Arab Republic</option>
<option value=762> Tajikistan</option>
<option value=764> Thailand</option>
<option value=768> Togo</option>
<option value=772> Tokelau</option>
<option value=776> Tonga</option>
<option value=780> Trinidad and Tobago</option>
<option value=784> United Arab Emirates</option>
<option value=788> Tunisia</option>
<option value=792> Turkey</option>
<option value=795> Turkmenistan</option>
<option value=796> Turks and Caicos Islands</option>
<option value=798> Tuvalu</option>
<option value=800> Uganda</option>
<option value=804> Ukraine</option>
<option value=807> Macedonia, the former Yugoslav Republic of</option>
<option value=818> Egypt</option>
<option value=826> United Kingdom</option>
<option value=831> Guernsey</option>
<option value=832> Jersey</option>
<option value=833> Isle of Man</option>
<option value=834> Tanzania, United Republic of</option>
<option value=840> United States</option>
<option value=850> Virgin Islands, U.S.</option>
<option value=854> Burkina Faso</option>
<option value=858> Uruguay</option>
<option value=860> Uzbekistan</option>
<option value=894> Zambia</option>
</select>

%COUNTRY_SEL%</TD></TR>
<TR bgcolor=$_COLORS[2]><TD>$_CITY:</TD><TD><input type=text name=CITY value='%CITY%'> $_ZIP: <input type=text name=ZIP value='%ZIP%' size=8></TD></TR>
<TR bgcolor=$_COLORS[2]><TD>$_ADDRESS_STREET:</TD><TD><input type=text name=ADDRESS_STREET value='%ADDRESS_STREET%' ID='ADDRESS_STREET' size=45>
<!-- 
%ADDRESS_STREET_SEL% <a class=link_button title='$_ADD' href='#' 
onclick=\"window.open('$SELF_URL?qindex=69&header=1', 'help', 'height=550,width=450,resizable=0,scrollbars=yes,menubar=no, status=yes');\"
>$_ADD</a>
-->
</TD></TR>
<TR bgcolor=$_COLORS[2]><TD>$_ADDRESS_BUILD:</TD><TD><input type=text name=ADDRESS_BUILD value='%ADDRESS_BUILD%' ID='ADDRESS_BUILD'> $_ADDRESS_FLAT:<input type=text name=ADDRESS_FLAT value='%ADDRESS_FLAT%' ID='ADDRESS_FLAT' size=8></TD></TR>

