$_QUARTER='Quarter';
$_SIX_MONTH='Six month';
$_LAST_ABON='Last Abon payment';
$_NEXT_ABON='Next Abon payment';
$_NONFIX_PERIOD='NonFixed Periods';
$_NOTIFICATION='Notification days';
$_DAYS_TO_END='Days to end';
$_ENDED='Finished';
$_SEND_ACCOUNT='Send account';